const data = {
  last_update: "2022-03-29",
  total_province: 34,
  provinces: [
    {
      id: 1,
      kota: "Jakarta",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 2,
      kota: "Jawa Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 3,
      kota: "Jawa Tengah",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 4,
      kota: "Jawa Timur",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 5,
      kota: "Banten",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 6,
      kota: "Yogyakarta",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 7,
      kota: "Kalimantan Timur",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 8,
      kota: "Bali",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 9,
      kota: "Sumatera Utara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 10,
      kota: "Riau",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 11,
      kota: "Sulawesi Selatan",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 12,
      kota: "Sumatera Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 13,
      kota: "Nusa Tenggara Timur",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 14,
      kota: "Kalimantan Selatan",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 15,
      kota: "Sumatera Selatan",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 16,
      kota: "Lampung",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 17,
      kota: "Kepulauan Riau",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 18,
      kota: "Bangka Belitung",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 19,
      kota: "Kalimantan Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 20,
      kota: "Sulawesi Tengah",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 21,
      kota: "Kalimantan Tengah",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 22,
      kota: "Sulawesi Utara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 23,
      kota: "Papua",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 24,
      kota: "Kalimantan Utara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 25,
      kota: "Aceh",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 26,
      kota: "Jambi",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 27,
      kota: "Nusa Tenggara Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 28,
      kota: "Papua Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 29,
      kota: "Bengkulu",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 30,
      kota: "Sulawesi Tenggara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 31,
      kota: "Maluku",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 32,
      kota: "Sulawesi Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 33,
      kota: "Maluku Utara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      id: 34,
      kota: "Gorontalo",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
  ],
};

export default data;
